"""Source-grounded portfolio content. Run build.py after edits."""
from urllib.parse import quote

def source(repo, path='', label='View source'):
    kind = 'blob' if path.endswith(('.py', '.java', '.cs', '.lua', '.sh', '.md')) else 'tree'
    return {'label': label, 'url': f'https://github.com/voostorm/{repo}' + (f'/{kind}/main/' + quote(path, safe='/') if path else '/')}

TTU = 'Projects/individual/Object-Oriented Programming & Design/Iteration 2/IT_2_turned-in_completed/wlee44-dashboard_2'
DRP = 'Projects/team/Software Engineering/drp'
IR = 'CSCI 572 - Information Retrieval and Web Search Engines'

PROJECTS = [
 dict(id='demand-response', title='Demand Response Portal', category='Backend & web', filters='web systems', year='2023', context='Team capstone · Tennessee Tech', stack=['Python', 'Flask', 'MariaDB', 'Docker'], visual='portal',
      summary='An energy-data web platform, with backend APIs for managing organizations, users, and meters.',
      problem='Power consumers and providers need a way to organize meter data and explore energy usage. Our capstone team built a web portal for those workflows.',
      contribution='My primary responsibility was the backend API for the administrator and organization pages. I worked on operations that add, update, and retrieve the records those pages display.',
      details=['Seven route handlers across the administrator and organization API modules cover organization lists, member updates, meter assignment, and creation operations.', 'Used SQL queries and joins to retrieve organization members, update records, and return JSON responses to the frontend.', 'Worked in an Agile team over roughly six months. The shared application includes Flask, MariaDB, Redis, Nginx, and Docker Compose.'],
      outcome='A team-built capstone connecting web interfaces, API behavior, and relational data. The linked modules show my main area of contribution.',
      proof=[source('ttu-works',DRP+'/src/web/app/routes/api/admin/adminpage.py','Administrator API'),source('ttu-works',DRP+'/src/web/app/routes/api/org/organization.py','Organization API'),source('ttu-works',DRP,'Project repository')]),
 dict(id='web-crawler',title='Concurrent Web Crawler',category='Data & AI',filters='ai systems',year='Spring 2025',context='Individual coursework · USC',stack=['Python','Threads & queues','Beautiful Soup','CSV / JSON'],visual='crawler',
      summary='A multithreaded crawler and search-evaluation workflow that turn web pages into inspectable data.',
      problem='Collecting web pages requires controlling traversal, handling unreliable requests, and recording what was actually fetched.',
      contribution='Implemented a Python crawler with a shared URL queue, worker threads, depth and domain checks, request timeouts, and CSV reports. In a related assignment, I compared search results across 100 queries.',
      details=['Configured seven worker threads and used locks around shared counters and output operations.', 'Recorded fetch status, content type, file size, and outgoing links, with separate reports for encountered and visited URLs.', 'The companion evaluation script exports search results as JSON and computes overlap and rank-correlation statistics in CSV.'],
      outcome='Inspectable collection and evaluation artifacts, with practical experience in concurrency, HTTP failure handling, parsing, and data reporting.',
      proof=[source('usc-works',IR+'/web-crawling/web-crawling-submission/crawler.py','Crawler implementation'),source('usc-works',IR+'/compare-search-engines/compare-search-engines-submission','Search evaluation')]),
 dict(id='schedule-dashboard',title='Academic Schedule Dashboard',category='Backend & web',filters='web',year='Spring 2022',context='Individual coursework · Tennessee Tech',stack=['Java','Spring Boot','Maven','JUnit'],visual='dashboard',
      summary='Java services that turn course schedules into filtered results and credit-hour summaries.',
      problem='Raw course data needs to be organized by subject, faculty, section, and term before it is useful in an academic dashboard.',
      contribution='Built backend service methods across three coursework iterations, consuming a schedule service and exposing query results through Spring Boot GET endpoints.',
      details=['The final ServiceBridge defines 13 GET mappings, including course, faculty, subject, and term-based queries.', 'Returned domain objects and Java collections such as SemesterSchedule, CourseInstance, and ArrayList for different query shapes.', 'Included seven JUnit tests in the final iteration for multi-term, faculty, subject, and course lookup behavior.'],
      outcome='A concrete example of object-oriented modeling, service integration, API design, and testing. The coursework depends on its original schedule service.',
      proof=[source('ttu-works',TTU+'/src/main/java/edu/tntech/csc2310/dashboard/ServiceBridge.java','Service implementation'),source('ttu-works',TTU+'/src/test/java/edu/tntech/csc2310/dashboard/ServiceBridgeTest.java','JUnit tests'),source('ttu-works',TTU,'Project & build instructions')]),
 dict(id='addon-engineering',title='Arena Addon Engineering',category='Systems & tools',filters='systems games',year='2026',context='Personal modifications · Existing open-source addons',stack=['Lua','Event handling','UI state','Debugging'],visual='addons',
      summary='Practical fixes to the tools I use: predictable cooldown ordering, configuration, and combat feedback.',
      problem='In a fast arena match, inconsistent icon order or incorrect cooldown visibility makes game state harder to read.',
      contribution='Maintain personal modifications to existing World of Warcraft addons, including OmniCD, GladiusEx, and NameplateCooldowns. I define the behavior I need, investigate problems, and iterate on fixes with AI assistance.',
      details=['Added saved drag ordering and test-mode configuration so cooldown layouts can be prepared ahead of play.', 'Worked on specialization, talent, and party-composition conditions that control cooldown visibility and ordering.', 'Adjusted cooldown baselines and repaired configuration and display behavior across multiple addons.'],
      outcome='An ongoing maintenance project driven by actual use: translating UI problems into event, state, and configuration changes. Original addon authors retain credit for the underlying projects.',
      proof=[source('mop-addons','OmniCD/Modules/Party/Reorder.lua','Saved icon ordering'),source('mop-addons','OmniCD/Modules/Party/GroupInfo.lua','Party and ability state'),source('mop-addons','','Browse addon modifications')]),
 dict(id='prime-engine',title='C++ Engine Systems',category='Games & graphics',filters='games systems',year='Fall 2024',context='Coursework · USC CSCI 522',stack=['C++','Lua','PrimeEngine','Maya'],visual='engine',
      summary='Work below the gameplay layer: view-frustum culling, collision, animation blending, and NPC states.',
      problem='An interactive 3D scene depends on coordinated rendering, movement, animation, and behavior systems.',
      contribution='Implemented engine and gameplay milestones in the course-provided PrimeEngine, integrating C++ logic with Lua hooks and Maya-exported assets.',
      details=['Added AABB bounding volumes and plane-based frustum rejection, with a focused scene and debug visualization for checking culling.', 'Implemented gravity and collision response for character and environment interaction.', 'Worked on full-body, partial-body, and additive animation blending, plus waypoint patrol and aim-at behavior transitions.'],
      outcome='Experience extending an existing C++ engine across several interacting subsystems. The public repository contains a written milestone outline, rather than engine source or an executable demo.',
      proof=[source('usc-works','CSCI 522 - Game Engine Development/outline.md','Read milestone outline')]),
 dict(id='fish-fish',title='Fish Fish',category='Games & graphics',filters='games',year='Oct–Dec 2025',context='6-person team · 2 months · USC',stack=['Unity','C#','WebGL','Firebase'],visual='fish',video='WDgjX7Pozf0',play='https://voostorm.github.io/fish-fish-playable/',
      summary='A fishing-combat roguelike with a cast, hook, and reel loop—and playtest telemetry.',
      problem='Our team explored how fishing could become an active combat mechanic, with dodging, timing, and room-to-room progression.',
      contribution='Contributed to the fishing-rod combat loop, enemy behaviors, progression systems, and playtest event logging in a six-person Unity project.',
      details=['The game combines charged casting, hook detection, and reeling with distinct enemy movement and attack patterns.', 'Runs connect ocean rooms with coins and shop upgrades for range, reel speed, and survivability.', 'The project includes UnityWebRequest-based logging to Firebase and a Google Apps Script / Google Sheets endpoint for playtest analysis.'],
      outcome='A playable Unity WebGL team project. The public copy provides project code; the original course repository and detailed team commit history are private.',
      proof=[source('fish-fish','','Project source'),source('fish-fish','Assets/Scripts/GoogleSheetsLogger.cs','Playtest logging')]),
 dict(id='rag-workflows',title='Retrieval & Local AI Workflows',category='Data & AI',filters='ai',year='Spring 2025',context='Individual coursework · USC',stack=['Ollama','LangFlow','RAG','MCP'],visual='rag',
      summary='Hands-on experiments with local language models, retrieval pipelines, and connected tools.',
      problem='Language-model workflows become more useful when they can retrieve relevant material or interact with tools beyond the prompt.',
      contribution='Completed coursework exercises involving local LLM use, a visual retrieval workflow, local-file retrieval, and tool-assisted search.',
      details=['Used Ollama for local model experiments and LangFlow to construct a retrieval-augmented generation workflow.', 'Explored Claude Desktop with MCP for local-file access and search-tool integration.', 'Preserved submitted workflow and result screenshots as evidence of the experiments.'],
      outcome='Practical familiarity with assembling AI workflows. These are coursework demonstrations, with screenshots available in the repository.',
      proof=[source('usc-works',IR+'/LLM+RAG/LLM+RAG-submission','Submitted workflows & results'),source('usc-works',IR+'/LLM+RAG/LLM+RAG-instructions.md','Assignment context')]),
 dict(id='go-agent',title='Adversarial Go Agent',category='Data & AI',filters='ai games',year='Fall 2024',context='Individual coursework · USC',stack=['Python','Alpha-beta search','Heuristics','Iterative deepening'],visual='go',
      summary='A small-board Go agent that weighs candidate moves under a search-time budget.',
      problem='A turn-based game agent must choose useful moves while balancing search depth against limited decision time.',
      contribution='Implemented a Go-playing agent with iterative deepening, alpha-beta search, opening moves, and a position-evaluation function.',
      details=['Evaluated positions using stone counts and liberties, and explored candidate legal moves.', 'Set a maximum search depth and a time limit, with checks during move selection.', 'Included fallback behavior for a legal move or pass when the search does not produce a move.'],
      outcome='A focused implementation of adversarial search and heuristic decision-making. Running it requires the assignment’s game harness.',
      proof=[source('usc-works','CSCI 561 - Foundations of Artificial Intelligence/GO/solutions/stage2_my_player3.py','Agent implementation')]),
 dict(id='linux-tools',title='Linux & Network Utilities',category='Systems & tools',filters='systems',year='Fall 2022',context='Individual coursework · Tennessee Tech',stack=['Bash','Linux','SSH / DNS','Google Cloud VMs'],visual='terminal',
      summary='Shell scripts for host selection, network diagnostics, and everyday Unix workflows.',
      problem='Routine system checks are easier to repeat when common commands are organized into a small utility.',
      contribution='Wrote Bash scripts in Unix labs using Google Cloud virtual machines, including a menu-driven network helper.',
      details=['Read hosts from a file and offered host selection for ping and DNS queries.', 'Added menu paths for SSH, hostname, and network-interface inspection.', 'Practiced arguments, loops, conditions, and file processing in supporting lab scripts.'],
      outcome='Hands-on foundations in command-line automation and network troubleshooting, demonstrated through coursework scripts.',
      proof=[source('ttu-works','Coursework/Intro to DevOps with Unix/wlee44_lab06/nethelper lab 06.sh','Network helper'),source('ttu-works','Coursework/Intro to DevOps with Unix','Unix coursework')]),
 dict(id='library-database',title='Library Database Application',category='Backend & web',filters='web',year='Fall 2022',context='Individual coursework · Tennessee Tech',stack=['Java','JDBC','MySQL','SQL'],visual='database',
      summary='A relational library system for books, members, loans, returns, and overdue payments.',
      problem='Library records connect many entities: books and authors, physical copies, members, loans, and payments.',
      contribution='Completed a multipart database project and built a Java command-line application that queries and updates a MySQL library database through JDBC.',
      details=['Implemented menu-driven workflows for borrowing, returning, and renewing book copies.', 'Used prepared statements and SQL joins to retrieve related records and member loan details.', 'Included queries and updates for overdue balances and payment registration.'],
      outcome='Practice translating relational data into usable application workflows, with SQL and Java application code available for review.',
      proof=[source('ttu-works','Projects/individual/Database Management Systems/Project 3/dbms_project3_turn-in_completed/src/project3.java','Java / JDBC implementation'),source('ttu-works','Projects/individual/Database Management Systems','Database project stages')]),
 dict(id='magnet-bomber',title='Magnet Bomber',category='Games & graphics',filters='games',year='Sep 2025',context='3-person team · 2 weeks · USC',stack=['Unity','C#','Raycasts','WebGL'],visual='magnet',video='ZR_4xCYwzhk',play='https://voostorm.github.io/magnet-bomber-playable/',
      summary='An arena prototype built around pulling and launching bombs to set up explosions.',
      problem='Our team prototyped a combat loop where magnetic interactions change how the player positions bombs and handles threats.',
      contribution='Worked on a Unity arena prototype with player controls, bomb behavior, targeting feedback, and collision handling.',
      details=['The player controller combines mouse-directed movement, rotation, boundary clamping, and aim/readiness indicators.', 'Bomb behavior includes launch speed, acceleration, bounce, lifetime, and explosion radius.', 'Layer-masked raycasts and line-rendered indicators support targeting and interaction feedback.'],
      outcome='A playable WebGL prototype delivered in a short team project. The original course repository and detailed commit history are private; a public display copy is linked below.',
      proof=[source('magnet-bomber','','Project source')]),
 dict(id='zap',title='Zap',category='Games & graphics',filters='games',year='Personal project',context='Solo · AI-assisted development',stack=['Python','Pygame','Game loop','Collision detection'],visual='zap',video='Szx1nL-O3BQ',
      summary='A minimalist survival shooter: dodge incoming squares, fire in eight directions, and try again.',
      problem='I wanted to turn a simple survival-game idea into a complete interactive loop while learning game programming.',
      contribution='Designed and built a Pygame shooter with generative-AI assistance, covering movement, projectiles, enemy spawning, and the restart flow.',
      details=['Implemented the start-screen, gameplay, game-over, and retry states.', 'Added procedural enemy spawning with speed and spawn-rate changes over time.', 'Included projectile and enemy updates, collision detection, and a survival timer.'],
      outcome='A small locally runnable Python game with a recorded demo. The repository includes installation instructions; there is no hosted playable build.',
      proof=[source('zap','','Source & run instructions')]),
]
